version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Paris"
    groups:
      docker-dependencies:
        patterns:
          - "github.com/docker/cli"
          - "github.com/docker/docker"
    labels:
      - "kind/dependencies"
      - "bot"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Paris"
    labels:
      - "kind/dependencies"
      - "bot"
